language: python

python:
  - "3.6"
cache: pip

install:
  - pip install -r requirements.txt

services:
  - postgresql

before_script:
  - psql -c "CREATE DATABASE politico;" -U postgres
  - psql -c "CREATE DATABASE politicotest;" -U postgres

env:
  - DATABASE_URL="postgres://postgres:njaguara@localhost:5432/politico" DATABASE_TEST_URL="dbname='politicotest' host='localhost' port='5432' user='postgres' password='njaguara'"

script:
  - pytest app/tests --cov=app
  
after_success:
  - coveralls